# PrimeChecker coded by Primer_Legend with Love ♥♥♥
#
# Coder from SandBox Studio
# coded for you this cool plugin!
#
# Команды
#
# /check [ник] - вызвать игрока на проверку (primechecker.admin)
# /check ban [ник] - забанить игрока который на проверке (primechecker.admin)
# /check discord [ник-админа] [дискорд] - отправить дискорд админу (primechecker.use)
# /uncheck [ник] - снять игрока с проверки (primechecker.admin)
# /cheater - сознаться в читах (primechecker.use)

# Если у игрока нету права primechecker.use или primechecker.admin
no-permission: "&cУ вас не достаточно прав!"

# Верхняя строчка тайтла при вызове на проверку.
title: "&cВас вызвали на проверку!"

# Нижняя строчка тайтла при вызове на проверку.
subtitle: "&7У вас есть 5 минут чтобы написать дискорд"

# Если команду ввели в консоль.
not-player: "&cИспользуйте команду от имени игрока!"

# Если игрок ввёл дискорд (отправляется админу)
send-discord-admin: "&aДискорд игрока: %discord%"

# Если игрок ввёл дискорд (отправляется игроку)
send-discord-player: "&aВы отправили админу свой дискорд"

# Если админ ввёл /check ban [ник] (отправляется админу)
check-ban: "&cВы заблокировали игрока которого проверяли!"

# Если игрок ввёл команду кроме (/cheater, /uncheck) при проверке
disabled-chat: "&cВы не можете использовать чат при проверке!"

# Если админ вызвал игрока на проверку (отправляется админу)
check-execute-admin: "&cВы вызвали на проверку игрока %player%!"

# Если игрока вызвали на проверку (отправляется в чат)
# %admin% возвращает ник админка
check-execute:
  - "&cВас вызвали на проверку, используйте команду:"
  - "&c/check discord %admin% [Ваш дискорд]"
  - "&cЛибо /cheater чтобы сознать в читах"
  - "&cЕсли вы будете игнорировать через %minutes% минут вы будете забанены!"

# Если админ ввёл команду /uncheck [ник] (отправляется игроку)
uncheck-player: "&aВы прошли проверку, админ вас отпустил!"

# Если админ ввёл команду /uncheck [ник] (отправляется админу)
uncheck-admin: "&aВы отпустили игрока!"

# Если игрок которого вызвали на проверку вышел (отправляется админу)
player-leave: "&cИгрок которого вы вызвали на проверку вышел и получил наказание!"

# Время, которое есть у игрока сознаться либо указать дискорд.
# Указывать в минутах!
time: 5

# Список команд которые будут введены в консоль если игрок
# выйдет из игры при проверке либо у него закончится время.
# %player% возвращает ник игрока
commands:
  - ban %player% 15d

# Список команд которые будут введены в консоль если игрок
# сознается в читах.
# %player% возвращает ник игрока
commands-confess:
  - ban %player% 15d